madewithlove/semver

- .gitignore
- app/Semver/Application.php
- app/Semver/Http/Controllers/PackageController.php
- app/Semver/Services/Error/ServiceProvider.php
- app/Semver/Services/Packagist/Packagist.php
- app/Semver/Services/Packagist/ServiceProvider.php
- app/routes.php
- composer.json
- public/app/js/app.js
- resources/views/_partials/social.php
- resources/views/index.php
* Moved code out of the controller.
* Used GET instead of POST for matching versions.
* Tweet button
* Link releases to releases, instead of source
* Added defaultContstraint, which is what composer would add to composer.json if you didn't add a contstraint to composer require command. Is not yet represented in the front-end
* Added `minimum-stability` get param to change outcome of filter.
> Add implementation with feature flags

- public/app/sass/layout/_footer.scss
- resources/views/_partials/footer.php
- resources/views/_partials/social.php
- resources/views/index.php
- Move social buttons to footer
---
Before/After. Depends what you think, merge if you think it's better, close otherwise
> Move social buttons to footer

- public/app/js/app.js
- public/app/sass/layout/_search.scss
- resources/views/index.php
- Default constraint is now used as base constraint when switching package
- Default constraint is now shown in placeholder of version input
- Tweak form styles to make the difference between placeholder/value more visible
---
Closes #3
> Show default constraint in front-end

- public/app/js/app.js
- resources/views/index.php
- Fixed link to branches
---
Closes #5
> Properly link to branches

- app/Semver/Application.php
- app/Semver/Services/Cache/ServiceProvider.php
- app/Semver/Services/Packagist/Packagist.php
- app/Semver/Services/Paths/ServiceProvider.php
- cache/.gitignore
- composer.json
- composer.lock
- [internal] Cache versions fetched from Packagist
---
This will be needed for #4 as we'll need a way to hit the same endpoint multiple times rapidly without refetching all versions every time (which would be really slow).
Lifetime is set to a day, not sure if we should make that longer/shorter.
> Cache versions fetched from Packagist

- app/Semver/Http/Controllers/PackageController.php
- app/Semver/Services/Packagist/Packagist.php
- public/app/js/app.js
- public/app/sass/layout/_search.scss
- resources/views/index.php
- Add minimum stability dropdown
---
Closes #11
> Add minimum stability dropdown

- resources/views/_partials/footer.php
> Link to changehub

- composer.lock
* Install most recent version of composer
> Updated composer

- public/app/js/Controllers/AppController.js
* Links to releases readded again.
--
fixes #26
> Readded link to tags

- app/Semver/Services/Packagist/Packagist.php
* Now parse branch aliases and replace dev-branchname with their alias.
> Refactored some to have better sorting of versions and replace dev-branch with branch aliases

- resources/views/_layout/global.php
- Make font loading protocol independent
> Protocol independent asset loading

- resources/views/_partials/footer.php
This PR updates the link in the `footer.php` partial view. The old link was returning `404` 😱 
Thanks for a great tool!
> Update footer.php with correct link to playground page

- app/Semver/Application.php
- app/Semver/Http/Controllers/PackageController.php
- package-lock.json
- The app was crashing on the word `phar` in the URI
---
For some reason, league/route crashes when you use the term `phar` in a URI.  In this dirty hack, I replace it before it gets to the router. 
solves #57
> Phar issue

- .env.example
- .gitignore
- app/Semver/Application.php
- composer.json
- composer.lock
- [internal] Added support for .env files
> Add support for .env files

- .env.example
- .gitignore
- app/Semver/Application.php
- app/Semver/Services/Error/ServiceProvider.php
- app/Semver/Services/Error/SimplePageHandler.php
- composer.json
- composer.lock
- Custom error page for production environment
> Custom error page

- resources/views/_layout/global.php
- resources/views/_partials/footer.php
- Updated header and footer links
> Correct links in header and footer

- .github/workflows/ci.yml
- app/Version/Matcher.php
- composer.json
- composer.lock
- resources/views/livewire/semver-checker.blade.php
- tests/Unit/Version/MatcherTest.php
This merge request adds a simple version matcher that checks if package versions match the defined constraint and stability
> Determine if versions match

- app/Http/Livewire/SemverChecker.php
- resources/views/livewire/semver-checker.blade.php
- tests/Unit/Version/MatcherTest.php
This PR;
- removes unused imports,
- fixes unit test namespace,
- fixes the variable `$package` comparison in blade template (since it's not nullable),
- corrects closing blade directives.
> Minor fixes

- app/Version/Version.php
- resources/views/livewire/semver-checker.blade.php
This PR;
- uses readonly properties instead of getters,
- uses conditional class blade directive.
> Readonly properties

- README.md
> Let's make README awesome!

- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.2.0` branch.
**Before merging**, you need to:
- Checkout the `shift-ci-v11.2.0` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))
> Laravel 11.2.0 Shift

- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.7.0` branch.
**Before merging**, you need to:
- Checkout the `shift-ci-v11.7.0` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))
> Laravel 11.7.0 Shift

- app/Livewire/SemverChecker.php
Fixes https://github.com/madewithlove/semver/issues/483
> Increase strictness on constraint validation

- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.9.2` branch.
**Before merging**, you need to:
- Checkout the `shift-ci-v11.9.2` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))
> Laravel 11.9.2 Shift

- .github/workflows/ci.yml
- app/Packagist/ApiClient.php
- app/Packagist/CachedApiClient.php
- app/Version/Matcher.php
- app/Version/Parser.php
- app/Version/Version.php
- app/VirtualPackages/VirtualPackageEnrichingApiClient.php
- app/VirtualPackages/VirtualPackageVersion.php
- tests/Feature/HomeTest.php
- tests/Unit/Version/MatcherTest.php
This will be required in phpunit 12
> Replace annotations with attributes

- .github/workflows/ci.yml
- app/VirtualPackages/VirtualPackageFactory.php
- composer.json
- composer.lock
- Upgraded PHP to the latest version.
> Upgrade PHP to 8.4 🐘

- public/css/app.css
- resources/views/home.blade.php
- resources/views/livewire/semver-checker.blade.php
- Upgraded Tailwind CSS to v4.
> Upgrade Tailwind CSS to v4
